### ISSUE TITLE
getRIn values off when temperature around 0 C

### ISSUE THREAD

**Issue by p-doyle** [SequentMicrosystems/megaioind-rpi#2]
I use the below with the getRInK() function to convert the 10K temperature sensor resistance to C:

`value = 1 / (1 / 298.15 + (1 / 3977.0) * math.log(resVal / 10.0)) - 273.15`

Everything is fine until the temperature drops to around 0 C, which is around 32768 ohms, and that causes the c2() function inside getRInK() to subtract 65536 from the resistance value, causing it to go negative.  Is that the intended behavior?  I noticed that the command line tool does not do this subtraction and returns the expected value.

**Comment by alexburcea2877** [comment]
You are correct, the resistance read functions return unsigned values and  "c2()" (2's complement) function  must not be called.
Thanks.

**Comment by alexburcea2877** [comment]
Solve
