### ISSUE TITLE
Update to python3 format

### ISSUE THREAD

**Issue by Grandpa-G** [SequentMicrosystems/megaioind-rpi#4]
Please update to Python3

Tabs and spaces are not allowed in python3. 

<> is not valid
>>> import megaioind
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/megaioind-rpi/python/megaioind/megaioind/__init__.py", line 213
    if(val <> 0):
            ^
SyntaxError: invalid syntax

**Comment by alexburcea2877** [comment]
Thank you for comment, we solve the compatibility issues.

**Comment by alexburcea2877** [comment]
Please confirm problem solved, for closing the issue.

**Comment by Grandpa-G** [comment]
Confirmed
